production:
  solr:
    hostname: localhost
    port: 8987
    log_level: WARNING

development:
  solr:
    hostname: localhost
    port: 8988
    log_level: INFO

test:
  solr:
    hostname: localhost
    port: 8989
    log_level: WARNING
