
development:
  solr:
    hostname: localhost
    port: 8988
    log_level: INFO
    solr_home: <%= "#{Rails.root}/solr" %>
    path: /solr/development
#/Users/jakewendt/github_repo/jakewendt/active_record_sunspotter/solr

#    solr_home: solr
#    path: /Users/jakewendt/github_repo/jakewendt/active_record_sunspotter/solr/data/development

#
#	'solr_home' MUST be absolute or will get a bunch of ...
#	Caused by: java.io.IOException: Cannot create directory: /opt/local/lib/ruby2.0/gems/2.0.0/gems/sunspot_solr-2.1.0/solr/solr/./development/data/index
#
#
#	Don't understand the purpose of 'path' yet. But need it and don't change it.
#	The code is suggestive that it is not necessary, but in actuality seems to be.
#	Too many 'solr' directories, I can't keep 'em straight.
#

test:
  solr:
    hostname: localhost
    port: 8989
    log_level: WARNING
    path: /solr/test
    solr_home: <%= "#{Rails.root}/solr" %>
#    solr_home: /Users/jakewendt/github_repo/jakewendt/active_record_sunspotter/solr

#    solr_home: solr
#    path: /Users/jakewendt/github_repo/jakewendt/active_record_sunspotter/solr/data/test

